name: Build and Push Docker Image

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU (for ARM builds)
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push multi-platform Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm/v7 \
          -t gfonseca/hacktab:latest \
          -t gfonseca/hacktab:latest-arm \
          --push .