name: Build and Push Docker Image

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        docker build -t gfonseca/hacktab:$VERSION .

    - name: Push Docker image to Docker Hub
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        docker push gfonseca/hacktab:$VERSION
